"""added types

Revision ID: 26079f3cea8b
Revises: 
Create Date: 2022-02-23 23:55:15.226171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26079f3cea8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addhousetypess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('desc', sa.String(length=250), nullable=False),
    sa.Column('short_name', sa.String(length=250), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addrobjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fias_id', sa.Integer(), nullable=False),
    sa.Column('fias_object_id', sa.BigInteger(), nullable=False),
    sa.Column('fias_object_guid', sa.String(length=50), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addrobjects_fias_object_id'), 'addrobjects', ['fias_object_id'], unique=False)
    op.create_table('addrobjecttypess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('desc', sa.String(length=250), nullable=False),
    sa.Column('short_name', sa.String(length=250), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appartemntstypess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('desc', sa.String(length=250), nullable=False),
    sa.Column('short_name', sa.String(length=250), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houseobjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fias_id', sa.Integer(), nullable=False),
    sa.Column('fias_object_id', sa.BigInteger(), nullable=False),
    sa.Column('fias_object_guid', sa.String(length=50), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('house_num', sa.String(length=250), nullable=False),
    sa.Column('add_num_1', sa.String(length=250), nullable=False),
    sa.Column('add_num_2', sa.String(length=250), nullable=False),
    sa.Column('house_type', sa.Integer(), nullable=False),
    sa.Column('add_type_1', sa.Integer(), nullable=False),
    sa.Column('add_type_2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houseobjects_fias_object_id'), 'houseobjects', ['fias_object_id'], unique=False)
    op.create_table('housetypess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('desc', sa.String(length=250), nullable=False),
    sa.Column('short_name', sa.String(length=250), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roomtypess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('desc', sa.String(length=250), nullable=False),
    sa.Column('short_name', sa.String(length=250), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomtypess')
    op.drop_table('housetypess')
    op.drop_index(op.f('ix_houseobjects_fias_object_id'), table_name='houseobjects')
    op.drop_table('houseobjects')
    op.drop_table('appartemntstypess')
    op.drop_table('addrobjecttypess')
    op.drop_index(op.f('ix_addrobjects_fias_object_id'), table_name='addrobjects')
    op.drop_table('addrobjects')
    op.drop_table('addhousetypess')
    # ### end Alembic commands ###
