"""init

Revision ID: 66ee9097c6e9
Revises: 
Create Date: 2022-02-23 16:54:30.063470

"""
from alembic import op
import sqlalchemy as sa

sa.dialects.postgresql.UUID()
from sqlalchemy.dialects.postgresql import UUID
# revision identifiers, used by Alembic.
revision = '66ee9097c6e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addrobjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('object_guid', UUID(as_uuid=True), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houseobjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('object_guid', UUID(as_uuid=True), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('house_num', sa.String(length=250), nullable=False),
    sa.Column('add_num_1', sa.String(length=250), nullable=False),
    sa.Column('add_num_2', sa.String(length=250), nullable=False),
    sa.Column('house_type', sa.Integer(), nullable=False),
    sa.Column('add_type_1', sa.Integer(), nullable=False),
    sa.Column('add_type_2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houseobjects')
    op.drop_table('addrobjects')
    # ### end Alembic commands ###
